version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 2.2
    build:
        commands:
            - 'dotnet publish --output staging/site'
    post_build:
        commands:
            - 'cp aws-windows-deployment-manifest.json staging'
artifacts:
    base-directory: 'staging'
    files:
        - '**/*'
    discard-paths: no
