version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 2.2
    build:
        commands:
            - 'dotnet publish --output build'
    post_build:
        commands:
            - 'zip -r build.zip build'
            - 'zip deployfiles.zip aws-windows-deployment-manifest.json build.zip'
artifacts:
    files:
        - 'deployfiles.zip'
    discard-paths: no
