version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 2.2
    build:
        commands:
            - 'dotnet publish --output site'
    post_build:
        commands:
            - 'cd site'
            - 'zip ../site.zip *'
            - 'cd ..'
            - 'zip deployfiles.zip site.zip aws-windows-deployment-manifest.json'
artifacts:
    files:
        - 'deployfiles.zip'
    discard-paths: no
