version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 2.2
    build:
        commands:
            - 'dotnet publish --output build'
    post_build:
        commands:
            - 'cd build'
            - 'zip ../build.zip *'
            - 'cd ..'
            - 'zip deployfiles.zip build.zip aws-windows-deployment-manifest.json'
artifacts:
    files:
        - 'deployfiles.zip'
    discard-paths: no
